server:
  port: 18888

knife4j:
  enable: true

debug: false

jasypt:
  encryptor:
    password: root
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      prefix: ENC(
      suffix: )

spring:
  datasource:
      mysql:
        jdbc-url: jdbc:mysql://localhost:3306/sjtc?useAffectedRows=true&useSSL=false&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: ENC(mISU4LC0jGV5N1Uljn4RlA==)
        driver-class-name: com.mysql.cj.jdbc.Driver
#      phoenix:
#        jdbc-url: jdbc:phoenix:127.0.0.1:2181
#        username:
#        password:
#        driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
      # spring-boot 2.X 默认采用高性能的 Hikari 作为连接池
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        # 池中维护的最小空闲连接数
        minimum-idle: 10
        # 池中最大连接数，包括闲置和使用中的连接
        maximum-pool-size: 20
        # 此属性控制从池返回的连接的默认自动提交行为。默认为 true
        auto-commit: true
        # 允许最长空闲时间
        idle-timeout: 30000
        # 此属性表示连接池的用户定义名称，主要显示在日志记录和 JMX 管理控制台中，以标识池和池配置。 默认值：自动生成
        pool-name: custom-hikari
        #此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000 即 30 分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认 30 秒，即 30000
        connection-timeout: 30000
        # 连接测试 sql 这个地方需要根据数据库方言差异而配置 例如 oracle 就应该写成  select 1 from dual
        connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  groovy:
    template:
      check-template-location: false
  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #时间戳统一转换为指定格式
    time-zone: GMT+8 # 时区修改为东8区
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: sjtc-server

shiro:
  web:
    enabled: true
  enabled: true

logging:
  file:
    name: sjtc.log
groovyResource: /groovyScript

#hitqz:
#  device:
#    hkcamera:
#      hc-net-sdk-path: G:\hgdN-sjtc\device\hk-camera-device\src\main\resources\faceLibs\HCNetSDK.dll
#      n-log-level: 3
#      b-auto-del: false
#      sdk-log-path: .\SDKLog\
#      save-photo-path: H:\



